sudo: false
language: python
cache:
    directories:
      - $HOME/.cache/pip

env:
    global:
        - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
        - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

matrix:
    include:
        - python: 2.6
          env: TOXENV=py26
        - python: 2.7
          env: TOXENV=py27
        - python: 2.7
          env: TOXENV=docs
        - python: 2.7
          env: TOXENV=docs-spellcheck
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - python: 2.7
          env: TOXENV=docs-linkcheck
        - python: 2.7
          env: TOXENV=lint
    allow_failures:
      - env: TOXENV=docs-linkcheck

install:
  - travis_retry ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - "source ~/.venv/bin/activate && codecov"

branches:
  only:
    - master
    - gh-pages
